SELECT MP.MEMBER_NAME, RR.REVIEW_TEXT, DATE_FORMAT(RR.REVIEW_DATE,'%Y-%m-%d')AS REVIEW_DATE
FROM 
    (
        SELECT MEMBER_ID
            ,RANK() OVER(ORDER BY COUNT(*) DESC) AS RANKING
        FROM REST_REVIEW
        GROUP BY MEMBER_ID
     )A
JOIN REST_REVIEW RR ON A.MEMBER_ID=RR.MEMBER_ID
JOIN MEMBER_PROFILE MP ON A.MEMBER_ID=MP.MEMBER_ID
WHERE A.RANKING = 1
ORDER BY RR.REVIEW_DATE, RR.REVIEW_TEXT