-- 코드를 입력하세요
    
-- 2. 해당기간동안의 월별 자동차 ID별 총 대여 횟수 리스트 출력
SELECT MONTH(START_DATE)AS MONTH, CAR_ID, COUNT(*)AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE >='2022-08-01' AND START_DATE <='2022-10-31'
    -- 1. 대여시작일을 기준으로 2022년 8월부터 2022년 10월까지 총 대여횟수가 5회 이상인 자동차들
    AND CAR_ID IN (SELECT CAR_ID
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                WHERE START_DATE >='2022-08-01'AND START_DATE <='2022-10-31'
                GROUP BY CAR_ID
                HAVING COUNT(*)>=5)
-- 3. 정렬
GROUP BY CAR_ID, MONTH(START_DATE)
HAVING COUNT(*)<>0
ORDER BY MONTH, CAR_ID DESC