-- 코드를 입력하세요
WITH HOURS AS(
    SELECT TO_CHAR(LEVEL-1,'FM99') AS HOUR
    FROM DUAL
    CONNECT BY LEVEL<=24
)
SELECT H.HOUR, NVL(C.COUNT, 0)AS COUNT
FROM HOURS H LEFT JOIN(
    SELECT TO_CHAR(DATETIME,'FMHH24')AS HOUR, COUNT(*)AS COUNT
    FROM ANIMAL_OUTS
    
    GROUP BY TO_CHAR(DATETIME,'FMHH24')
)C
ON H.HOUR=C.HOUR
WHERE H.HOUR BETWEEN 9 AND 19
ORDER BY TO_NUMBER(H.HOUR)