--30일 이상 대여 가능한 세단, SUV
-- 11월에 대여가 가능한 세단, SUV
SELECT A.CAR_ID, A.CAR_TYPE, (A.DAILY_FEE *30)*(1 - B.DISCOUNT_RATE / 100) AS FEE
FROM(SELECT RCC.CAR_ID, RCC.CAR_TYPE, RCC.DAILY_FEE
FROM CAR_RENTAL_COMPANY_CAR RCC
WHERE NOT EXISTS (
    SELECT 1
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY RCRH
    WHERE RCRH.CAR_ID = RCC.CAR_ID
        AND RCRH.START_DATE <= TO_DATE('2022-11-30', 'YYYY-MM-DD')
        AND RCRH.END_DATE >= TO_DATE('2022-11-01', 'YYYY-MM-DD')
)
AND (RCC.CAR_TYPE='세단' OR RCC.CAR_TYPE='SUV'))A
JOIN 
(SELECT *
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
WHERE (CAR_TYPE='세단' OR CAR_TYPE='SUV') AND DURATION_TYPE LIKE '30%') B
ON A.CAR_TYPE=B.CAR_TYPE
GROUP BY A.CAR_ID, A.CAR_TYPE, A.DAILY_FEE, B.DISCOUNT_RATE
HAVING (A.DAILY_FEE *30)*(1 - B.DISCOUNT_RATE / 100) >= 500000 AND (A.DAILY_FEE *30)*(1 - B.DISCOUNT_RATE / 100) <=2000000
ORDER BY FEE DESC, A.CAR_TYPE, A.CAR_ID DESC
    
