-- 코드를 작성해주세요
SELECT SUM(GRA.SCORE) AS SCORE, EMP.EMP_NO, EMP.EMP_NAME, EMP.POSITION, EMP.EMAIL
FROM HR_EMPLOYEES AS EMP JOIN HR_GRADE AS GRA
ON EMP.EMP_NO = GRA.EMP_NO
WHERE GRA.YEAR ="2022"
GROUP BY GRA.EMP_NO
ORDER BY SCORE DESC
LIMIT 1;
