SELECT B.APNT_NO,A.PT_NAME, A.PT_NO, B.MCDP_CD, B.DR_NAME, B.APNT_YMD
FROM
    (SELECT APP.APNT_NO, D.MCDP_CD, D.DR_NAME, APP.APNT_YMD--진료예약번호, 진료과코드, 의사이름, 진료예약일시,(예약취소날짜)
FROM DOCTOR D JOIN APPOINTMENT APP
ON D.DR_ID=APP.MDDR_ID
WHERE APP.MCDP_CD='CS'
     AND APP.APNT_CNCL_YN='N'
)B
JOIN
    (SELECT P.PT_NAME, P.PT_NO, APP.APNT_NO
    FROM PATIENT P JOIN APPOINTMENT APP
    ON P.PT_NO=APP.PT_NO)A
ON B.APNT_NO=A.APNT_NO
WHERE TO_CHAR(B.APNT_YMD, 'YYYY-MM-DD')='2022-04-13'
ORDER BY APNT_YMD