-- 코드를 입력하세요
SELECT CATEGORY, PRICE, PRODUCT_NAME
FROM
    (SELECT CATEGORY, PRICE, PRODUCT_NAME, RANK() OVER(PARTITION BY CATEGORY ORDER BY PRICE DESC)AS RNK
FROM FOOD_PRODUCT
WHERE CATEGORY ='과자' OR CATEGORY ='국' OR CATEGORY ='김치' OR CATEGORY ='식용유')
WHERE RNK=1
ORDER BY PRICE DESC