-- 코드를 입력하세요
--7월 아이스크림 총 주문량
SELECT FLAVOR
FROM (
    SELECT J.FLAVOR, (J.TOTAL_ORDER + FH.TOTAL_ORDER)AS TOTAL
FROM
(SELECT FLAVOR, SUM(TOTAL_ORDER)AS TOTAL_ORDER
FROM JULY
GROUP BY FLAVOR)J
JOIN
-- 상반기 아이스크림 총 주문량
(SELECT FLAVOR, TOTAL_ORDER
FROM FIRST_HALF)FH
ON J.FLAVOR=FH.FLAVOR
GROUP BY J.FLAVOR, J.TOTAL_ORDER + FH.TOTAL_ORDER
)A
ORDER BY TOTAL DESC
FETCH FIRST 3 ROWS ONLY;

