-- 코드를 작성해주세요
SELECT B.FISH_COUNT, B.MAX_LENGTH, A.FISH_TYPE
FROM(SELECT FISH_TYPE, AVG(LENGTH)AS AVG_LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE  
    HAVING AVG_LENGTH>=33) A
JOIN
    (SELECT COUNT(*) AS FISH_COUNT, MAX(LENGTH)AS MAX_LENGTH, FISH_TYPE
        FROM FISH_INFO
        GROUP BY FISH_TYPE) B
ON A.FISH_TYPE=B.FISH_TYPE
ORDER BY FISH_TYPE