-- 코드를 입력하세요
SELECT DISTINCT CAR.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CAR 
    JOIN 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY RENTAL
    ON CAR.CAR_ID = RENTAL.CAR_ID
WHERE CAR_TYPE ='세단'
    AND TO_CHAR(START_DATE,'YYYYMM')='202210'
ORDER BY CAR.CAR_ID DESC;
