WITH HOUR AS(
    SELECT TO_CHAR(LEVEL-1,'FM99')AS HOUR
    FROM DUAL
    CONNECT BY LEVEL <=24
)
SELECT H.HOUR, NVL(C.COUNT,0)AS COUNT
FROM HOUR H LEFT JOIN (
    SELECT TO_CHAR(DATETIME,'FMHH24')AS HOUR, COUNT(*) AS COUNT 
    FROM ANIMAL_OUTS
    GROUP BY TO_CHAR(DATETIME,'FMHH24')
) C
ON H.HOUR=C.HOUR
ORDER BY TO_NUMBER(H.HOUR)