-- 코드를 입력하세요
SELECT *
FROM (
	SELECT AO.ANIMAL_ID, AO.NAME
	FROM ANIMAL_INS AI JOIN ANIMAL_OUTS AO
	ON AI.ANIMAL_ID = AO.ANIMAL_ID
	WHERE AO.ANIMAL_ID IS NOT NULL
	ORDER BY AO.DATETIME-AI.DATETIME DESC
)
WHERE ROWNUM<=2

--AO.DATETIME-AI.DATETIME 이 가장 큰 순으로 정렬 수 두마리만 추출(그 값이 큰 순서대로)