SELECT TO_CHAR(SALES_DATE,'YYYY')AS YEAR
    , TO_CHAR(SALES_DATE,'FMmm')AS MONTH
    , GENDER
    , COUNT(DISTINCT UI.USER_ID) USERS
FROM USER_INFO UI JOIN ONLINE_SALE OS
ON UI.USER_ID=OS.USER_ID
WHERE GENDER IS NOT NULL
GROUP BY TO_CHAR(SALES_DATE,'YYYY'), TO_CHAR(SALES_DATE,'FMmm'),GENDER
ORDER BY YEAR, TO_NUMBER(MONTH), GENDER