-- 코드를 입력하세요

SELECT TO_CHAR(SALES_DATE,'YYYY')AS YEAR
    ,TO_CHAR(SALES_DATE,'FMmm')AS MONTH
    ,COUNT(DISTINCT(USER_ID))AS PURCHASED_USERS
    -- 2021년도에 가입한 회원 구하기
    ,ROUND(COUNT(DISTINCT(USER_ID)) /(SELECT COUNT(USER_ID)
        FROM USER_INFO
        WHERE TO_CHAR(JOINED,'YYYY')='2021'),1)AS PUCHASED_RATIO
FROM ONLINE_SALE
WHERE USER_ID IN (SELECT USER_ID
                  FROM USER_INFO
                  WHERE TO_CHAR(JOINED,'YYYY')='2021')
GROUP BY TO_CHAR(SALES_DATE,'YYYY'), TO_CHAR(SALES_DATE,'FMmm')
ORDER BY YEAR, TO_NUMBER(MONTH)