-- 코드를 입력하세요
SELECT AO.ANIMAL_ID, AO.NAME
FROM ANIMAL_INS AI, ANIMAL_OUTS AO
WHERE AI.ANIMAL_ID(+) = AO.ANIMAL_ID --RIGNT OUTER JOIN
AND AI.ANIMAL_ID IS NULL --AI테이블에 AO테이블에 없는 레코드는 NULL이 출력. 그 NULL인 부분이 유실된 부분이지 않을까...
ORDER BY ANIMAL_ID;

