-- 1단계: 리뷰 수 집계 + 랭킹 부여
WITH REVIEW_COUNT AS (
    SELECT 
        RR.MEMBER_ID, 
        COUNT(*) AS CNT_REVIEW
    FROM REST_REVIEW RR
    GROUP BY RR.MEMBER_ID
),
-- 2단계: 상위 랭커 MEMBER_ID 추출
TOP_RANKERS AS (
    SELECT 
        MEMBER_ID,
        DENSE_RANK() OVER (ORDER BY CNT_REVIEW DESC) AS RANKING
    FROM REVIEW_COUNT
    WHERE CNT_REVIEW IS NOT NULL
),
-- 3단계: 원본 리뷰 데이터와 조인
FINAL_REVIEW AS (
    SELECT 
        RR.MEMBER_ID,
        RR.REVIEW_TEXT,
        TO_CHAR(RR.REVIEW_DATE, 'YYYY-MM-DD') AS REVIEW_DATE
    FROM REST_REVIEW RR
    JOIN TOP_RANKERS TR ON RR.MEMBER_ID = TR.MEMBER_ID
    WHERE TR.RANKING = 1
)

-- 4단계: 사용자 이름과 최종 출력
SELECT 
    MP.MEMBER_NAME,
    FR.REVIEW_TEXT,
    FR.REVIEW_DATE
FROM 
    FINAL_REVIEW FR
    JOIN MEMBER_PROFILE MP ON FR.MEMBER_ID = MP.MEMBER_ID
ORDER BY 
    MP.MEMBER_NAME, FR.REVIEW_DATE, FR.REVIEW_TEXT;
