-- 코드를 작성해주세요
WITH DEVELOPER_GRADE AS (
    SELECT ID, GROUP_CONCAT(NAME) AS NAME -- 매칭된 기술명을 GROUP_CONCAT으로 합침
        ,GROUP_CONCAT(CATEGORY) AS CATEGORY
    FROM DEVELOPERS D
    JOIN SKILLCODES S
    ON D.SKILL_CODE & S.CODE = S.CODE -- 개발자의 기술코드에 해당 기술이 포함되어있는가?
    GROUP BY ID
)
SELECT CASE
        WHEN NAME LIKE '%Python%' AND CATEGORY LIKE '%Front%' THEN 'A'
        WHEN NAME LIKE '%C#%'THEN 'B'
        WHEN CATEGORY LIKE '%Front%' THEN 'C'
        END AS GRADE, DG.ID, D.EMAIL
FROM DEVELOPER_GRADE DG
    JOIN DEVELOPERS D
    ON DG.ID=D.ID
HAVING GRADE IS NOT NULL
ORDER BY 1,2;
