WITH HIST AS (
  SELECT
    A.CAR_TYPE,
    A.DAILY_FEE,
    B.HISTORY_ID,
    B.END_DATE - B.START_DATE + 1 AS DURATION,
    CASE 
      WHEN B.END_DATE - B.START_DATE + 1 >= 90 THEN '90일 이상'
      WHEN B.END_DATE - B.START_DATE + 1 >= 30 THEN '30일 이상'
      WHEN B.END_DATE - B.START_DATE + 1 >= 7 THEN '7일 이상'
      ELSE NULL
    END AS DURATION_TYPE
  FROM CAR_RENTAL_COMPANY_CAR A
  JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
    ON A.CAR_ID = B.CAR_ID
  WHERE A.CAR_TYPE = '트럭'
)
SELECT
  H.HISTORY_ID,
  FLOOR(
    H.DAILY_FEE 
    * H.DURATION 
    * (100 - NVL(P.DISCOUNT_RATE, 0)) / 100
  ) AS FEE
FROM HIST H
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
  ON H.CAR_TYPE = P.CAR_TYPE
    AND H.DURATION_TYPE = P.DURATION_TYPE
ORDER BY FEE DESC, H.HISTORY_ID DESC;
