-- 코드를 작성해주세요
SELECT INFO.ITEM_ID, INFO.ITEM_NAME, INFO.RARITY
FROM ITEM_INFO INFO JOIN ITEM_TREE TREE
ON INFO.ITEM_ID=TREE.ITEM_ID
WHERE NOT EXISTS (
    SELECT 1 
    FROM ITEM_TREE TREE 
    WHERE TREE.PARENT_ITEM_ID = INFO.ITEM_ID
)
ORDER BY INFO.ITEM_ID DESC

