-- 코드를 입력하세요
WITH COUNTLIKE AS (
    SELECT FOOD_TYPE, MAX(FAVORITES)AS MAX_FAV
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)
SELECT A.FOOD_TYPE, A.REST_ID, A.REST_NAME, A.FAVORITES
FROM REST_INFO A
JOIN COUNTLIKE B
ON A.FOOD_TYPE=B.FOOD_TYPE
AND A.FAVORITES = B.MAX_FAV
ORDER BY FOOD_TYPE DESC