-- 코드를 작성해주세요
#  SELECT A.EMP_NO, A.EMP_NAME, B.GRADE
#     , CASE 
#     WHEN GRADE='S' THEN SAL*0.2
#     WHEN GRADE='A' THEN SAL*0.15 
#     WHEN GRADE='B' THEN SAL*0.1
#     WHEN GRADE='C' THEN 0
#     END AS BONUS
# FROM
#         (SELECT EMP.EMP_NO, EMP.EMP_NAME, DEPT.DEPT_ID, EMP.POSITION, EMP.SAL, DEPT.DEPT_NAME_KR
#         FROM HR_EMPLOYEES EMP JOIN HR_DEPARTMENT DEPT
#         ON EMP.DEPT_ID=DEPT.DEPT_ID)A
#     JOIN 
#         (SELECT EMP_NO
#             , CASE WHEN SCORE >=96 THEN 'S'
#             WHEN SCORE >=90 AND SCORE <96 THEN 'A'
#             WHEN SCORE >=80 AND SCORE <90 THEN 'B'
#             WHEN SCORE < 80 THEN 'C'
#             END AS GRADE
#         FROM HR_GRADE) B
# ON A.EMP_NO=B.EMP_NO
# ORDER BY EMP_NO
SELECT 
    E.EMP_NO,
    E.EMP_NAME,
    CASE 
        WHEN AVG_GRADE >= 96 THEN 'S'
        WHEN AVG_GRADE >= 90 THEN 'A'
        WHEN AVG_GRADE >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    CASE 
        WHEN AVG_GRADE >= 96 THEN E.SAL * 0.2
        WHEN AVG_GRADE >= 90 THEN E.SAL * 0.15
        WHEN AVG_GRADE >= 80 THEN E.SAL * 0.1
        ELSE 0
    END AS BONUS
FROM HR_EMPLOYEES E
JOIN (
    SELECT EMP_NO, AVG(SCORE) AS AVG_GRADE
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO
) G ON E.EMP_NO = G.EMP_NO
ORDER BY E.EMP_NO;
